C11=(1/2).*(armAngVel.*(2.*HCAxy.*cos(2.*(armAng+boomAng))+(HCAxx+(-1).* ...
  HCAyy).*sin(2.*(armAng+boomAng))+(-2).*mCA.*rCAEx.*(rAfx+rEAx.*cos( ...
  boomAng)+rCAEx.*cos(aCA+armAng+boomAng)).*sin(aCA+armAng+boomAng))+ ...
  boomAngVel.*(2.*HCBxy.*cos(2.*boomAng)+2.*HCAxy.*cos(2.*(armAng+boomAng) ...
  )+HCBxx.*sin(2.*boomAng)+(-1).*HCByy.*sin(2.*boomAng)+(-2).*mCB.*rCBAx.* ...
  (rAfx+rCBAx.*cos(aCB+boomAng)).*sin(aCB+boomAng)+HCAxx.*sin(2.*(armAng+ ...
  boomAng))+(-1).*HCAyy.*sin(2.*(armAng+boomAng))+(-2).*mCA.*(rAfx+rEAx.* ...
  cos(boomAng)+rCAEx.*cos(aCA+armAng+boomAng)).*(rEAx.*sin(boomAng)+ ...
  rCAEx.*sin(aCA+armAng+boomAng))));
C12=armAngVel.*(HCAxz.*cos(armAng+boomAng)+(-1).*HCAyz.*sin(armAng+boomAng)) ...
  +boomAngVel.*(HCBxz.*cos(boomAng)+HCAxz.*cos(armAng+boomAng)+(-1).* ...
  HCByz.*sin(boomAng)+(-1).*HCAyz.*sin(armAng+boomAng))+(1/2).*phiVel.*( ...
  2.*HCBxy.*cos(2.*boomAng)+2.*HCAxy.*cos(2.*(armAng+boomAng))+HCBxx.*sin( ...
  2.*boomAng)+(-1).*HCByy.*sin(2.*boomAng)+(-2).*mCB.*rCBAx.*(rAfx+rCBAx.* ...
  cos(aCB+boomAng)).*sin(aCB+boomAng)+HCAxx.*sin(2.*(armAng+boomAng))+(-1) ...
  .*HCAyy.*sin(2.*(armAng+boomAng))+(-2).*mCA.*(rAfx+rEAx.*cos(boomAng)+ ...
  rCAEx.*cos(aCA+armAng+boomAng)).*(rEAx.*sin(boomAng)+rCAEx.*sin(aCA+ ...
  armAng+boomAng)));
C13=HCAxy.*phiVel.*cos(2.*(armAng+boomAng))+armAngVel.*(HCAxz.*cos(armAng+ ...
  boomAng)+(-1).*HCAyz.*sin(armAng+boomAng))+boomAngVel.*(HCAxz.*cos( ...
  armAng+boomAng)+(-1).*HCAyz.*sin(armAng+boomAng))+(1/2).*(HCAxx+(-1).* ...
  HCAyy).*phiVel.*sin(2.*(armAng+boomAng))+(-1).*mCA.*phiVel.*rCAEx.*( ...
  rAfx+rEAx.*cos(boomAng)+rCAEx.*cos(aCA+armAng+boomAng)).*sin(aCA+armAng+ ...
  boomAng);
