C31=(1/2).*phiVel.*((-2).*HCAxy.*cos(2.*(armAng+boomAng))+((-1).*HCAxx+ ...
  HCAyy).*sin(2.*(armAng+boomAng))+2.*mCA.*rCAEx.*(rAfx+rEAx.*cos(boomAng) ...
  +rCAEx.*cos(aCA+armAng+boomAng)).*sin(aCA+armAng+boomAng));
C32=boomAngVel.*mCA.*rCAEx.*rEAx.*sin(aCA+armAng);
C33=0;
