D11=Hfzz+HCByy.*cos(boomAng).^2+mCB.*(rAfx+rCBAx.*cos(aCB+boomAng)).^2+ ...
  HCAyy.*cos(armAng+boomAng).^2+mCA.*(rAfx+rEAx.*cos(boomAng)+rCAEx.*cos( ...
  aCA+armAng+boomAng)).^2+HCBxx.*sin(boomAng).^2+HCBxy.*sin(2.*boomAng)+ ...
  HCAxx.*sin(armAng+boomAng).^2+HCAxy.*sin(2.*(armAng+boomAng));
D12=HCByz.*cos(boomAng)+HCAyz.*cos(armAng+boomAng)+HCBxz.*sin(boomAng)+ ...
  HCAxz.*sin(armAng+boomAng);
D13=HCAyz.*cos(armAng+boomAng)+HCAxz.*sin(armAng+boomAng);
