C21=(1/2).*phiVel.*((-2).*HCBxy.*cos(2.*boomAng)+(-2).*HCAxy.*cos(2.*( ...
  armAng+boomAng))+(-2).*HCbxy.*cos(2.*(armAng+bckAng+boomAng))+(-1).* ...
  HCBxx.*sin(2.*boomAng)+HCByy.*sin(2.*boomAng)+2.*mCB.*rCBAx.*(rAfx+ ...
  rCBAx.*cos(aCB+boomAng)).*sin(aCB+boomAng)+(-1).*HCAxx.*sin(2.*(armAng+ ...
  boomAng))+HCAyy.*sin(2.*(armAng+boomAng))+2.*mCA.*(rAfx+rEAx.*cos( ...
  boomAng)+rCAEx.*cos(aCA+armAng+boomAng)).*(rEAx.*sin(boomAng)+rCAEx.* ...
  sin(aCA+armAng+boomAng))+(-1).*HCbxx.*sin(2.*(armAng+bckAng+boomAng))+ ...
  HCbyy.*sin(2.*(armAng+bckAng+boomAng))+2.*mCb.*(rAfx+rEAx.*cos(boomAng)+ ...
  rIEx.*cos(armAng+boomAng)+rCbIx.*cos(aCb+armAng+bckAng+boomAng)).*( ...
  rEAx.*sin(boomAng)+rIEx.*sin(armAng+boomAng)+rCbIx.*sin(aCb+armAng+ ...
  bckAng+boomAng)));
C22=(-1).*armAngVel.*mCb.*rEAx.*rIEx.*sin(armAng)+(-1).*armAngVel.*mCA.* ...
  rCAEx.*rEAx.*sin(aCA+armAng)+(-1).*mCb.*rCbIx.*(bckAngVel.*rIEx.*sin( ...
  aCb+bckAng)+(armAngVel+bckAngVel).*rEAx.*sin(aCb+armAng+bckAng));
C23=(-1).*(armAngVel+boomAngVel).*mCb.*rEAx.*rIEx.*sin(armAng)+(-1).*( ...
  armAngVel+boomAngVel).*mCA.*rCAEx.*rEAx.*sin(aCA+armAng)+(-1).*mCb.* ...
  rCbIx.*(bckAngVel.*rIEx.*sin(aCb+bckAng)+(armAngVel+bckAngVel+ ...
  boomAngVel).*rEAx.*sin(aCb+armAng+bckAng));
C24=(-1).*(armAngVel+bckAngVel+boomAngVel).*mCb.*rCbIx.*(rIEx.*sin(aCb+ ...
  bckAng)+rEAx.*sin(aCb+armAng+bckAng));
