C22=(-1).*armAngVel.*mCb.*rEAx.*rIEx.*sin(armAng)+(-1).*armAngVel.*mCA.* ...
  rCAEx.*rEAx.*sin(aCA+armAng)+(-1).*mCb.*rCbIx.*(bckAngVel.*rIEx.*sin( ...
  aCb+bckAng)+(armAngVel+bckAngVel).*rEAx.*sin(aCb+armAng+bckAng));
C23=(-1).*(armAngVel+boomAngVel).*mCb.*rEAx.*rIEx.*sin(armAng)+(-1).*( ...
  armAngVel+boomAngVel).*mCA.*rCAEx.*rEAx.*sin(aCA+armAng)+(-1).*mCb.* ...
  rCbIx.*(bckAngVel.*rIEx.*sin(aCb+bckAng)+(armAngVel+bckAngVel+ ...
  boomAngVel).*rEAx.*sin(aCb+armAng+bckAng));
C24=(-1).*(armAngVel+bckAngVel+boomAngVel).*mCb.*rCbIx.*(rIEx.*sin(aCb+ ...
  bckAng)+rEAx.*sin(aCb+armAng+bckAng));
