C31=(1/2).*phiVel.*((-2).*HCAxy.*cos(2.*(armAng+boomAng))+(-2).*HCbxy.*cos( ...
  2.*(armAng+bckAng+boomAng))+(-1).*HCAxx.*sin(2.*(armAng+boomAng))+ ...
  HCAyy.*sin(2.*(armAng+boomAng))+2.*mCA.*rCAEx.*(rAfx+rEAx.*cos(boomAng)+ ...
  rCAEx.*cos(aCA+armAng+boomAng)).*sin(aCA+armAng+boomAng)+(-1).*HCbxx.* ...
  sin(2.*(armAng+bckAng+boomAng))+HCbyy.*sin(2.*(armAng+bckAng+boomAng))+ ...
  2.*mCb.*(rAfx+rEAx.*cos(boomAng)+rIEx.*cos(armAng+boomAng)+rCbIx.*cos( ...
  aCb+armAng+bckAng+boomAng)).*(rIEx.*sin(armAng+boomAng)+rCbIx.*sin(aCb+ ...
  armAng+bckAng+boomAng)));
C32=(-1).*bckAngVel.*mCb.*rCbIx.*rIEx.*sin(aCb+bckAng)+boomAngVel.*rEAx.*( ...
  mCb.*rIEx.*sin(armAng)+mCA.*rCAEx.*sin(aCA+armAng)+mCb.*rCbIx.*sin(aCb+ ...
  armAng+bckAng));
C33=(-1).*bckAngVel.*mCb.*rCbIx.*rIEx.*sin(aCb+bckAng);
C34=(-1).*(armAngVel+bckAngVel+boomAngVel).*mCb.*rCbIx.*rIEx.*sin(aCb+ ...
  bckAng);
