C41=(1/2).*phiVel.*((-2).*HCbxy.*cos(2.*(armAng+bckAng+boomAng))+((-1).* ...
  HCbxx+HCbyy).*sin(2.*(armAng+bckAng+boomAng))+2.*mCb.*rCbIx.*(rAfx+ ...
  rEAx.*cos(boomAng)+rIEx.*cos(armAng+boomAng)+rCbIx.*cos(aCb+armAng+ ...
  bckAng+boomAng)).*sin(aCb+armAng+bckAng+boomAng));
C42=mCb.*rCbIx.*((armAngVel+boomAngVel).*rIEx.*sin(aCb+bckAng)+boomAngVel.* ...
  rEAx.*sin(aCb+armAng+bckAng));
C43=(armAngVel+boomAngVel).*mCb.*rCbIx.*rIEx.*sin(aCb+bckAng);
C44=0;
