D11=Hfzz+HCByy.*cos(boomAng).^2+mCB.*(rAfx+rCBAx.*cos(aCB+boomAng)).^2+ ...
  HCAyy.*cos(armAng+boomAng).^2+mCA.*(rAfx+rEAx.*cos(boomAng)+rCAEx.*cos( ...
  aCA+armAng+boomAng)).^2+HCbyy.*cos(armAng+bckAng+boomAng).^2+mCb.*(rAfx+ ...
  rEAx.*cos(boomAng)+rIEx.*cos(armAng+boomAng)+rCbIx.*cos(aCb+armAng+ ...
  bckAng+boomAng)).^2+HCBxx.*sin(boomAng).^2+HCBxy.*sin(2.*boomAng)+ ...
  HCAxx.*sin(armAng+boomAng).^2+HCAxy.*sin(2.*(armAng+boomAng))+HCbxx.* ...
  sin(armAng+bckAng+boomAng).^2+HCbxy.*sin(2.*(armAng+bckAng+boomAng));
D12=HCByz.*cos(boomAng)+HCAyz.*cos(armAng+boomAng)+HCbyz.*cos(armAng+bckAng+ ...
  boomAng)+HCBxz.*sin(boomAng)+HCAxz.*sin(armAng+boomAng)+HCbxz.*sin( ...
  armAng+bckAng+boomAng);
D13=HCAyz.*cos(armAng+boomAng)+HCbyz.*cos(armAng+bckAng+boomAng)+HCAxz.*sin( ...
  armAng+boomAng)+HCbxz.*sin(armAng+bckAng+boomAng);
D14=HCbyz.*cos(armAng+bckAng+boomAng)+HCbxz.*sin(armAng+bckAng+boomAng);
