D22=HCAzz+HCbzz+HCBzz+mCA.*rCAEx.^2+mCB.*rCBAx.^2+mCb.*rCbIx.^2+mCA.* ...
  rEAx.^2+mCb.*rEAx.^2+mCb.*rIEx.^2+2.*mCb.*rEAx.*rIEx.*cos(armAng)+2.* ...
  mCA.*rCAEx.*rEAx.*cos(aCA+armAng)+2.*mCb.*rCbIx.*rIEx.*cos(aCb+bckAng)+ ...
  2.*mCb.*rCbIx.*rEAx.*cos(aCb+armAng+bckAng);
D23=HCAzz+HCbzz+mCA.*rCAEx.^2+mCb.*rCbIx.^2+mCb.*rIEx.^2+mCb.*rEAx.*rIEx.* ...
  cos(armAng)+mCA.*rCAEx.*rEAx.*cos(aCA+armAng)+2.*mCb.*rCbIx.*rIEx.*cos( ...
  aCb+bckAng)+mCb.*rCbIx.*rEAx.*cos(aCb+armAng+bckAng);
D24=HCbzz+mCb.*rCbIx.^2+mCb.*rCbIx.*rIEx.*cos(aCb+bckAng)+mCb.*rCbIx.*rEAx.* ...
  cos(aCb+armAng+bckAng);
