G1=0;
G2=g.*((mCA+mCb).*rEAx.*cos(boomAng)+mCB.*rCBAx.*cos(aCB+boomAng)+mCb.* ...
  rIEx.*cos(armAng+boomAng)+mCA.*rCAEx.*cos(aCA+armAng+boomAng)+mCb.* ...
  rCbIx.*cos(aCb+armAng+bckAng+boomAng));
G3=g.*(mCb.*rIEx.*cos(armAng+boomAng)+mCA.*rCAEx.*cos(aCA+armAng+boomAng)+ ...
  mCb.*rCbIx.*cos(aCb+armAng+bckAng+boomAng));
G4=g.*mCb.*rCbIx.*cos(aCb+armAng+bckAng+boomAng);
