G1=0;
G2=g.*((mCA+mCb).*rEAx.*cos(tA(t))+mCB.*rCBAx.*cos(aCB+tA(t))+mCb.*rIEx.* ...
  cos(tA(t)+tE(t))+mCA.*rCAEx.*cos(aCA+tA(t)+tE(t))+mCb.*rCbIx.*cos(aCb+ ...
  tA(t)+tE(t)+tI(t)));
G3=g.*(mCb.*rIEx.*cos(tA(t)+tE(t))+mCA.*rCAEx.*cos(aCA+tA(t)+tE(t))+mCb.* ...
  rCbIx.*cos(aCb+tA(t)+tE(t)+tI(t)));
G4=g.*mCb.*rCbIx.*cos(aCb+tA(t)+tE(t)+tI(t));
